# Quick introduction to Julia

These examples are based on http://learnxinyminutes.com/docs/julia/. Assumes Julia 0.6.

## Types

There are different types of numbers.

In [106]:
typeof("mykel")

String

In [107]:
typeof(1.0)

Float64

In [108]:
typeof(1 + 1im)

Complex{Int64}

In [109]:
supertype(Float64)

AbstractFloat

In [110]:
supertype(AbstractFloat)

Real

In [111]:
supertype(Real)

Number

In [112]:
supertype(Number)

Any

In [113]:
supertype(Int64)

Signed

In [114]:
supertype(Signed)

Integer

In [115]:
supertype(Integer)

Real

Boolean types

In [116]:
typeof(true)

Bool

## Boolean Operators

Negation is done with !

In [117]:
!true

false

In [118]:
1 == 1

true

In [119]:
1 != 1

false

Comparisons can be chained

In [120]:
1 < 2 < 3

true

## Strings

Use double quotes for strings.

In [121]:
"This is a string"

"This is a string"

In [122]:
typeof("This is a string")

String

Use single quotes for characters.

In [123]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [124]:
typeof('a')

Char

In [125]:
"This is a string"[1] # note the 1-based indexing---similar to Matlab but unlike C/C++/Java

'T': ASCII/Unicode U+0054 (category Lu: Letter, uppercase)

$ can be used for "string interpolation"

In [126]:
"2 + 2 = $(2+2)"

"2 + 2 = 4"

In [127]:
using Printf
Printf.@printf "%d is less than %f" 4.5 5.3

5 is less than 5.300000

In [128]:
println("Welcome to Julia")

Welcome to Julia


## Variables

In [129]:
x = 5

5

Variable names start with a letter, but after that you can use letters, digits, underscores, and exclamation points.

In [130]:
xMarksTheSpot2Dig! = 1

1

## Arrays

In [131]:
a = Int64[]

0-element Array{Int64,1}

In [132]:
b = [4, 5, 6]

3-element Array{Int64,1}:
 4
 5
 6

In [133]:
b[1]

4

In [134]:
b[end-1]

5

In [135]:
matrix = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [136]:
a

0-element Array{Int64,1}

In [137]:
push!(a, 1)

1-element Array{Int64,1}:
 1

In [138]:
push!(a, 2)

2-element Array{Int64,1}:
 1
 2

In [139]:
append!(a, b)

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [140]:
a

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [141]:
pop!(a)

6

In [142]:
a

4-element Array{Int64,1}:
 1
 2
 4
 5

In [143]:
a[2:4]

3-element Array{Int64,1}:
 2
 4
 5

In [144]:
a[2:end]

3-element Array{Int64,1}:
 2
 4
 5

In [145]:
push!(a, round(Int64, 1.3))

5-element Array{Int64,1}:
 1
 2
 4
 5
 1

In [146]:
in(4, a)

true

In [147]:
4 in a

true

In [148]:
length(a)

5

## Tuples

In [149]:
a = (1, 5, 3)

(1, 5, 3)

In [150]:
typeof(a)

Tuple{Int64,Int64,Int64}

In [151]:
a[2]

5

In [152]:
#a[2] = 3 # can't change elements in a tuple

In [153]:
a, b, c = (1, 2, 3)

(1, 2, 3)

In [154]:
a

1

In [155]:
b

2

In [156]:
c

3

In [157]:
a, b, c = 1, 2, 3 # you can also leave off parentheses

(1, 2, 3)

In [158]:
a

1

In [159]:
b

2

In [160]:
c

3

In [161]:
(1,) # to create a single element tuple, you must add the "," at the end

(1,)

In [162]:
typeof((1,))

Tuple{Int64}

## Dictionaries

In [163]:
d = Dict()

Dict{Any,Any} with 0 entries

In [164]:
d = Dict("one"=>1, "two"=>2, "three"=>3)

Dict{String,Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [165]:
d["one"]

1

In [166]:
keys(d)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "two"
  "one"
  "three"

In [167]:
collect(keys(d))

3-element Array{String,1}:
 "two"  
 "one"  
 "three"

In [168]:
values(d)

Base.ValueIterator for a Dict{String,Int64} with 3 entries. Values:
  2
  1
  3

In [169]:
haskey(d, "one")

true

In [170]:
haskey(d, 1)

false

## Control Flow

In [171]:
# Let's make a variable
some_var = 5

# Here is an if statement. Indentation is not meaningful in Julia.
if some_var > 10
    println("some_var is totally bigger than 10.")
elseif some_var < 10    # This elseif clause is optional.
    println("some_var is smaller than 10.")
else                    # The else clause is optional too.
    println("some_var is indeed 10.")
end

some_var is smaller than 10.


In [172]:
# For loops iterate over iterables.
# Iterable types include Range, Array, Set, Dict, and String.
for animal in ["dog", "cat", "mouse"]
    println("$animal is a mammal")
    # You can use $ to interpolate variables or expression into strings
end

dog is a mammal
cat is a mammal
mouse is a mammal


In [173]:
for key_val in Dict("dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal")
    println("$(key_val[1]) is a $(key_val[2])")
end

mouse is a mammal
cat is a mammal
dog is a mammal


In [174]:
for (k,v) in Dict("dog"=>"mammal","cat"=>"mammal","mouse"=>"mammal")
    println("$k is a $v")
end

mouse is a mammal
cat is a mammal
dog is a mammal


In [175]:
x = 0
while x < 4
    global x
    println(x)
    x += 1  # Shorthand for x = x + 1
end

0
1
2
3


In [176]:
# Handle exceptions with a try/catch block
try
#    error("help")
catch e
   println("caught it $e")
end

## Functions

In [177]:
function add(x, y)
    println("x is $x and y is $y")
    # Functions return the value of their last statement (or where you specify "return")
    x + y
end
add(5, 6) 

x is 5 and y is 6


11

In [178]:
# You can define functions with optional positional arguments
function defaults(a,b,x=5,y=6)
    return "$a $b and $x $y"
end

defaults (generic function with 3 methods)

In [179]:
defaults('h','g')

"h g and 5 6"

In [180]:
defaults('h','g','j')

"h g and j 6"

In [181]:
defaults('h','g','j','k')

"h g and j k"

In [182]:
# You can define functions that take keyword arguments
function keyword_args(;k1=4,name2="hello") # note the ;
    return Dict("k1"=>k1,"name2"=>name2)
end

keyword_args (generic function with 1 method)

In [183]:
keyword_args(name2="ness")

Dict{String,Any} with 2 entries:
  "name2" => "ness"
  "k1"    => 4

In [184]:
keyword_args(k1="mine")

Dict{String,String} with 2 entries:
  "name2" => "hello"
  "k1"    => "mine"

In [185]:
keyword_args()

Dict{String,Any} with 2 entries:
  "name2" => "hello"
  "k1"    => 4

In [186]:
# This is "stabby lambda syntax" for creating anonymous functions
(x -> x > 2)(3) # => true

true

In [187]:
# This function is identical to create_adder implementation above.
function create_adder(x)
    y -> x + y
end

create_adder (generic function with 1 method)

In [188]:
# You can also name the internal function, if you want
function create_adder2(x)
    function adder(y)
        x + y
    end
    adder
end


create_adder2 (generic function with 1 method)

In [189]:
add_10 = create_adder(10)
add_10(3) 

13

In [190]:
map(add_10, [1,2,3])

3-element Array{Int64,1}:
 11
 12
 13

In [191]:
filter(x -> x > 5, [3, 4, 5, 6, 7])

2-element Array{Int64,1}:
 6
 7

In [192]:
[add_10(i) for i in [1, 2, 3]]

3-element Array{Int64,1}:
 11
 12
 13

## Composite Types

In [193]:
struct Tiger
  taillength::Float64
  coatcolor # not including a type annotation is the same as `::Any`
end

In [194]:
tigger = Tiger(3.5,"orange")

Tiger(3.5, "orange")

In [195]:
abstract type Cat end # just a name and point in the type hierarchy

In [196]:
subtypes(Number)

2-element Array{Any,1}:
 Complex
 Real   

In [197]:
subtypes(Cat)

2-element Array{Any,1}:
 Lion   
 Panther

In [198]:
# <: is the subtyping operator
struct Lion <: Cat # Lion is a subtype of Cat
    mane_color
    roar::String
end

In [199]:
# You can define more constructors for your type
# Just define a function of the same name as the type
# and call an existing constructor to get a value of the correct type
Lion(roar::String) = Lion("green",roar)
# This is an outer constructor because it's outside the type definition

Lion

In [200]:
struct Panther <: Cat # Panther is also a subtype of Cat
  eye_color
  Panther() = new("green")
  # Panthers will only have this constructor, and no default constructor.
end

In [201]:
subtypes(Cat)

2-element Array{Any,1}:
 Lion   
 Panther

## Multiple Dispatch

In [202]:
function meow(animal::Lion)
  animal.roar # access type properties using dot notation
end

function meow(animal::Panther)
  "grrr"
end

function meow(animal::Tiger)
  "rawwwr"
end

meow (generic function with 3 methods)

In [203]:
meow(tigger)

"rawwwr"

In [204]:
meow(Lion("brown","ROAAR"))

"ROAAR"

In [205]:
meow(Panther())

"grrr"

## Native Code

In [206]:
square(l) = l * l

square (generic function with 1 method)

In [207]:
square(5)

25

In [208]:
code_native(square, (Int32,))

	.section	__TEXT,__text,regular,pure_instructions
; Function square {
; Location: In[206]:1
; Function *; {
; Location: In[206]:1
	imull	%edi, %edi
;}
	movl	%edi, %eax
	retl
	nopw	%cs:(%eax,%eax)
;}


In [209]:
code_native(square, (Float64,))

	.section	__TEXT,__text,regular,pure_instructions
; Function square {
; Location: In[206]:1
; Function *; {
; Location: In[206]:1
	vmulsd	%xmm0, %xmm0, %xmm0
;}
	retl
	nopw	%cs:(%eax,%eax)
;}


In [210]:
code_llvm(square, (Int32,))


; Function square
; Location: In[206]:1
define i32 @julia_square_37551(i32) {
top:
; Function *; {
; Location: int.jl:54
  %1 = mul i32 %0, %0
;}
  ret i32 %1
}
